pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                echo 'Checking out...'
                git 'https://github.com/Filipe-A-Cruz/devops-23-24-JPE-PSM-1231828'
            }
        }
        stage('Assemble') {
            steps {
                dir('CA2/part2') {
                   echo 'Assembling...'
                   sh 'apt-get update -y'
                   sh 'apt-get install nodejs -y'
                   sh 'apt-get install npm -y'
                   sh 'rm -r node_modules'
                   sh 'npm install'
                   sh 'chmod u+x gradlew'
                   sh './gradlew clean assemble'
                }
            }
        }
        stage('Test') {
            steps {
                dir('CA2/part2') {
                    echo 'Testing...'
                    sh 'chmod u+x gradlew'
                    sh './gradlew test'
                }
            }
        }
        stage('Archive') {
            steps {
                dir('CA2/part2') {
                    echo 'Archiving...'
                    archiveArtifacts 'build/libs/*'
                }
            }
        }
        stage('Javadoc') {
            steps {
                dir('CA2/part2') {
                    echo 'Publishing Javadoc...'
                    sh 'chmod u+x gradlew'
                    sh './gradlew myJavadocs'
                    publishHTML([
                        allowMissing: false,
                        alwaysLinkToLastBuild: false,
                        keepAll: false,
                        reportDir: 'docs',
                        reportFiles: 'index.html',
                        reportName: 'Javadoc',
                        reportTitles: '',
                        useWrapperFileDirectly: true
                        ])
                }
            }
        }
        stage('Publish Image') {
            steps {
                dir('CA2/part2') {
                    echo 'Publishing Docker Image...'
                    def customImage = docker.build("ca5-part2-Filipe-A-Cruz:${env.BUILD_ID}")
                    customImage.push('latest')
                }
            }
        }
    }
}
